### ISSUE TITLE
Provide a css-only version

### ISSUE THREAD

**Issue by ingro** [LouisBarranqueiro/reapop-theme-wybo#1]
Hello! I'm trying to use reapop in my latest react-redux application but I can't use the provided themes because they require sass-loader and since I'm using [CRA](https://github.com/facebookincubator/create-react-app) (which is becoming increasingly popular) I have no way to add that loader, and in general I think that should be preferable to provide a standard css version because it would be more compatible with the various build pipeline that devs are using.

What do you think about it? The css version should be the default one or just an alternative? Maybe I can try to put up a PR for this issue but I would like to know your opinion first.

Thank you.

**Comment by LouisBarranqueiro** [comment]
Hey @ingro,

yeah, it would be good to do that for all themes. :) only provide css version for npm module. I'm gonna think about an implementation
