### ISSUE TITLE
The css variable has additional 'default' prop.

### ISSUE THREAD

**Issue by nikiqta** [LouisBarranqueiro/reapop-theme-wybo#17]
### Description
Hi I have recently migrate my project to works on:  
"webpack": "5.4.0",
"webpack-cli": "3.3.12"
"style-loader": "2.0.0",
"css-loader": "5.0.1",
"@babel/core": "7.12.3",
"@babel/polyfill": "7.12.1",
"@babel/preset-env": "7.12.1",
"@babel/preset-react": "7.12.5",

In the moment everything works fine except the "reapop-theme-wybo", the theme itself comes with classNames of "undefined".

### Explanation / motivation
I have checked the "reapop-theme-wybo/index.js" file and found out that the constant named "css" have a propperty called 'default' which contains all the classes. For example if I add everywhere css.default['some-class-name'] instead of css['some-class-name'] it works without issues.

When I try the approach to do something like this, for example -> const { default: css } = require('./lib/styles.module.css');
It works without any issues.
![image](https://user-images.githubusercontent.com/33606495/98927598-6a9f5300-24e1-11eb-9324-f6c3ade1ea8b.png)
![image](https://user-images.githubusercontent.com/33606495/98927637-7854d880-24e1-11eb-8fcc-1e00822ad4c2.png)

So, If you have time, could you check this and if possible to add it into a future update, please.

**The interesting part is that on :**
"webpack": "4.44.1",
"webpack-cli": "3.3.12",
"style-loader": "1.2.1",
"css-loader": "4.1.1",
"@babel/core": "7.11.0",
"@babel/polyfill": "7.10.4",
"@babel/preset-env": "7.11.0",
"@babel/preset-react": "7.10.4",

It is working fine.
![image](https://user-images.githubusercontent.com/33606495/98928626-ab4b9c00-24e2-11eb-82b2-d728336fff76.png)

### Additional information
I will add some screenshots to make it easier for getting all I said.

Here is how it looks like:

![image](https://user-images.githubusercontent.com/33606495/98926903-9241eb80-24e0-11eb-8d91-4e90cb56c9ee.png)

![image](https://user-images.githubusercontent.com/33606495/98926918-97069f80-24e0-11eb-86cd-ac245ec33300.png)

And here is example of what I mean:
![image](https://user-images.githubusercontent.com/33606495/98927218-ee0c7480-24e0-11eb-80bd-0427dd2575fd.png)

![image](https://user-images.githubusercontent.com/33606495/98927085-c2898a00-24e0-11eb-8ab1-802b2a451555.png)

**Comment by nikiqta** [comment]
Easy fix will be something like this:
const css = { ...(require('./lib/styles.module.css').default ? require('./lib/styles.module.css').default : require('./lib/styles.module.css'))};

It will work for all versions (Webpack, Babel, ..........):
![image](https://user-images.githubusercontent.com/33606495/98962852-b668f100-250f-11eb-9266-993b7230dcf6.png)

**Or something more readable:**

const classes = require('./lib/styles.module.css');
const css = { ...(classes.default ? classes.default : classes)};

![image](https://user-images.githubusercontent.com/33606495/98963351-31caa280-2510-11eb-87a0-21c96fa0ab94.png)

**Comment by LouisBarranqueiro** [comment]
👋 @nikiqta,

based on what you explained it seems to be an issue related to module types (commonjs, es6, etc...) and webpack/webpack loaders. For example, see the breaking changes introduced in the  [css-loader v4.0.0](https://github.com/webpack-contrib/css-loader/releases/tag/v4.0.0) where it uses ES modules syntax by default. You need to search for something in this direction.

**Comment by LouisBarranqueiro** [comment]
👋 I released a new version of Reapop where the themes are already included in the main package. This package is now deprecated.
