### ISSUE TITLE
Peer dependency bug with npm

### ISSUE THREAD

**Issue by raskyer** [LouisBarranqueiro/reapop-theme-wybo#4]
When trying to install this theme with reapop ^1.0.0. Got the following message:
`npm ERR! peerinvalid The package reapop does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer reapop-theme-wybo@0.4.0 wants reapop@^0.6.0`

Do you know how to fix that ? And why this theme as a peer outdated peer dependency ?

**Comment by LouisBarranqueiro** [comment]
Hey @LeaklessGfy, I'm gonna update peer dependencies of this theme. nothing changes for you, everything is working.

**Comment by LouisBarranqueiro** [comment]
just released the new version witht he fix. re-install this package and it will be good.
