### ISSUE TITLE
Errors "Module not found: Error: Can't resolve ..." in webpack config

### ISSUE THREAD

**Issue by ComicScrip** [LouisBarranqueiro/reapop-theme-wybo#7]
Hi !
Just spent half an hour figuring out why the webpack config given in the docs produced several errors like : 

```
./~/reapop-theme-wybo/index.js
Module not found: Error: Can't resolve 'css' 
```

It's just that newer versions of webpack require the "-loader" to be appended to the module name

So if there are people not very familiar to webpack like me, here's my working config : 

```
var CSSLoader = [
  'css-loader?sourceMap&-minimize',
  'modules',
  'importLoaders=1',
  'localIdentName=[name]__[local]__[hash:base64:5]'
].join('&');

module.exports = {
  module: {
    loaders: [{
      test: /\.css$/,
      loaders: ['style-loader', CSSLoader]
    }, {
      test: /\.woff(2)?(\?v=[0-9]\.[0-9]\.[0-9])?$/,
      loader: "url-loader?limit=10000&minetype=application/font-woff"
    }, {
      test: /\.(ttf|eot|svg)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
      loader: "file-loader"
    }]
  }
};
```

Except that, everything is working great so far :)

**Comment by joerodrig** [comment]
Submitted a fix to the readme for that here: https://github.com/LouisBarranqueiro/reapop-theme-wybo/pull/5
